TIMEOUT 30
DEFAULT primary

MENU TITLE L4T boot options

LABEL primary
      MENU LABEL primary kernel
      LINUX /EFI/BOOT/u-boot-app.efi
      FDT /tegra234-p3768-0000+p3767-0005.dtb
      APPEND gaiamode
